
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: banco_users
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
